version: "3"

services:
  internet-monitor:
    image: ghcr.io/swaggeroo/speedtest-monitor-influxdb
    restart: unless-stopped
    depends_on:
      - influxdb2
    environment:
      - ACCEPT_GDPR=<True> # IMPORTANT: https://www.speedtest.net/about/eula , https://www.speedtest.net/about/terms , https://www.speedtest.net/about/privacy
      - ACCEPT_LICENSE=<True> # IMPORTANT: https://www.speedtest.net/about/eula , https://www.speedtest.net/about/terms , https://www.speedtest.net/about/privacy
      - INFLUXDB_BUCKET=<Your Bucket>
      - INFLUXDB_HOST=<Your InfluxDB2 IP/Hostname>
      - INFLUXDB_ORG=<Your ORG>
      - INFLUXDB_PORT=8086
      - INFLUXDB_TOKEN=<Your Token>
      
      # Optional: Defaults seen below
      - INTERVAL=60
      - INFLUXDB_SSL=false
