name: Auto Build on Base Image Change

on:
  schedule:
    - cron: "0 0 3 * *"
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: library/golang:alpine
          image: flypenguin/homepage-builder # update for your image

      - name Export Variable
        id: exportvar
        run: echo "needs-updating=" >> $GITHUB_ENV && echo steps.baseupdatecheck.outputs.needs-updating >> $GITHUB_ENV


      # only execute subsequent steps if an update is actually NEEDED.
      # unfortunately we need to add an if-condition to all steps now
      # because a clean exit can't be triggered within a job it seems
      # (a cancellation is NOT the same and triggers a failure email)
      # see also https://github.com/actions/runner/issues/662